### ISSUE TITLE
update and test sensorml2iso

### ISSUE THREAD

**Issue by emiliom** [nanoos-pnw/ioos-ws#9]
@lsetiawan, please look into installing the latest [`sensorml2iso`](https://github.com/ioos/sensorml2iso) on nile (from conda forge, on a test conda env?) and testing it to make sure it works. Compare the output XML for one or two stations vs the corresponding output from the current `sensorml2iso` we're running operationally. There should be a couple of enhancements and fixes.

It'd be nice to be ready to upgrade by mid next week, unless you run into problems.

Mentioning #7, just for reference. We should probably close that issue, once we have captured all the useful information about our current operational setup.

**Comment by lsetiawan** [comment]
@emiliom Should this also go into the NANOOS-DMAC Documentation?

**Comment by emiliom** [comment]
Eventually, yes. But not anywhere near the level of detail found in issue #7! I think a single brief page dedicated to the WAFs and jobs for IOOS catalog registration is enough, listing the jobs we run, where they're found on nile, what service they target, and where the XML's go on data.nanoos.org. I can fill in and update the details later.

But this is now a separate topic/issue ... It'd be nice if phabricator had "issues"! How about if you add a page to the sphinx docs themselves, as a TO-DO list for us??

**Comment by lsetiawan** [comment]
I installed `sensorml2iso` from  conda-forge into a new conda environment, then trying to run it, I get a `TemplateNotFound` error:

```bash
$ sensorml2iso -s http://data.nanoos.org/52nsos/sos/kvp --output_dir $ISOPATH
Success, no errors returned from DescribeSensor requests in service: http://data.nanoos.org/52nsos/sos/kvp?acceptVersions=1.0.0&request=GetCapabilities&service=SOS
Traceback (most recent call last):
  File "/home/lsetiawan/miniconda/envs/test/bin/sensorml2iso", line 6, in <module>
    sys.exit(sensorml2iso.command_line.main())
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/command_line.py", line 98, in main
    obj.run()
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/sensorml2iso.py", line 171, in run
    self.generate_iso(stations_df)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/sensorml2iso.py", line 485, in generate_iso
    template = env.get_template('sensorml_iso.xml')
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sensorml_iso.xml
```

The Success before the error is so misleading.. Anyways, I went to `/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso` and `sensorml_iso.xml` is indeed nowhere to be found. 

```bash
$ ls /home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/
command_line.py  command_line.pyc  __init__.py  __init__.pyc  sensorml2iso.py  sensorml2iso.pyc
```

Looking at the main repo of this package, it seems like the `templates` folder did not get included in the conda package. https://github.com/ioos/sensorml2iso/tree/master/sensorml2iso

**Comment by emiliom** [comment]
Can you confirm that the conda package is based on the [latest release, 1.0.2](https://github.com/ioos/sensorml2iso/releases)? It looks that way on the [conda-forge recipe](https://github.com/conda-forge/sensorml2iso-feedstock)

Looking back at the [`sensorml2iso` README file](https://github.com/ioos/sensorml2iso/blob/master/README.md), I don't see a mention of conda. I assume you looked at that README file for the latest info on usage. And I remember some emails about their docker work; we can go that route if needed, but I prefer we first try to get it working via conda.

FYI, the templates seem to be at https://github.com/ioos/sensorml2iso/tree/master/sensorml2iso/templates, so it's odd that the conda packaging would not have included them.

If it looks like you did everything right and you have the latest version, please submit an issue on the sensorml2iso repo; ping Filipe on that issue, and link to this issue for reference.

**Comment by lsetiawan** [comment]
@emiliom I keep getting a 504 Error when running sensorml2iso:

```bash
(test) lsetiawan@nile:~$ ISOPATH=/home/lsetiawan/52nsos_test/
(test) lsetiawan@nile:~$ sensorml2iso -s http://data.nanoos.org/52nsos/sos/kvp --output_dir $ISOPATH
Traceback (most recent call last):
  File "/home/lsetiawan/miniconda/envs/test/bin/sensorml2iso", line 6, in <module>
    sys.exit(sensorml2iso.command_line.main())
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/command_line.py", line 98, in main
    obj.run()
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/sensorml2iso.py", line 131, in run
    stations_df = self.get_stations_df(self.service, self.stations)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/sensorml2iso.py", line 232, in get_stations_df
    sml_recs, sml_errors = sos_collector.metadata_plus_exceptions(output_format=fmt, timeout=200)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/pyoos/collectors/ioos/swe_sos.py", line 62, in metadata_plus_exceptions
    responses[feature] = (SensorML(self.server.describe_sensor(**ds_kwargs)))
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/owslib/swe/observation/sos100.py", line 139, in describe_sensor
    response = openURL(base_url, data, method, username=self.username, password=self.password, **url_kwargs).read()
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/owslib/util.py", line 189, in openURL
    req.raise_for_status()
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: http://data.nanoos.org/52nsos/sos/kvp?outputFormat=text%2Fxml%3B+subtype%3D%22sensorML%2F1.0.1%2Fprofiles%2Fioos_sos%2F1.0%22&version=1.0.0&request=DescribeSensor&procedure=urn%3Aioos%3Astation%3Ananoos%3Aapl_chaba&service=SOS
```

**Comment by emiliom** [comment]
We've been having problems with the SOS server. It's been down some of the time. But I thought it was doing fine this afternoon. I just tried a DescribeSensor request and can see that it's timing out, though. Hmm.

**Comment by lsetiawan** [comment]
@emiliom Thanks for letting me know. It works now, and after comparing 3 random xml files, it seems like the current xml's are more complete with information compared to the previous xml's that didn't use the package from `conda-forge`. When you give me an okay, I will switch over to the new code. Thanks!

**Comment by emiliom** [comment]
Great, thanks. I'm surprised it worked. It's pretty unstable -- I think it's probably extra slow right now, and running into time outs more frequently.

We'll discuss this next week, when I'm back.

**Comment by emiliom** [comment]
Did you complete the updated deployment? If so, just reply here and close the issue. Thanks.

**Comment by lsetiawan** [comment]
@emiliom Thanks for the reminder! Totally went past my radar. Doing the update now.

**Comment by lsetiawan** [comment]
conda environment that runs `sensorml2iso` in Nile  has been updated to use the conda package and will run tonight. Thanks.

**Comment by emiliom** [comment]
Thanks. I'm reopening the issue until we've confirmed that everything is working fine. So, hopefully we can close it again tomorrow!

**Comment by lsetiawan** [comment]
After double checking content in `./metadata/ioos/52nsos/` and opening one of the xml file. It appears that the script did indeed ran successfully. Closing this issue now.

**Comment by emiliom** [comment]
Thanks! Looks good.

But I'm going to reopen this issue mainly to leave it as a reminder to myself to follow up with IOOS on why the station "operator" is apparently not being pulled out clearly from SensorML, in the [IOOS Catalog](https://data.ioos.us/organization/nanoos), after we updated to the latest `sensorml2iso`. 

(Adding a link to a [relevant IOOS Catalog issue](https://github.com/ioos/catalog/issues/41))

You are done, though.

**Comment by emiliom** [comment]
In the IOOS Catalog, it looks like the "operator" (provider) information is in fact appearing in the Access section at the bottom. Under "Distributor" and "Originator". Here's [one example](https://data.ioos.us/dataset/penncoveshellfish-penn-cove-shellfish-coupeville-whidbey-island)

The Catalog faceting for operator/provider is not out yet (tracked in the IOOS Catalog issue I mentioned above).
